import React, {HTMLAttributes} from "react";
// TODO: style use type detection
import "../../../style/icon.css";
// Attention: This file is generated by "yarn icon", do not modify

export enum IconClass {
    HENGGONG = "ics-chenggong",
    RROW_LEFT = "ics-arrow-left",
    OWNLOAD = "ics-download",
    HECK = "ics-check",
    RROW_RIGHT = "ics-arrow-right",
    SIGN = "ics-asign",
    ETAIL = "ics-detail",
    XPORT = "ics-export",
    DD = "ics-add",
    LERM = "ics-alerm",
    MPORT = "ics-import",
    NLARGE = "ics-enlarge",
    ELETE = "ics-delete",
    LERM_I = "ics-alerm-i",
    DIT = "ics-edit",
    RDER_MANAGE = "ics-order-manage",
    ERVICE_MANAGE = "ics-service-manage",
    SERNAME = "ics-username",
    ENU = "ics-menu",
    ASSWORD = "ics-password",
    EMPORARY_STORAGE = "ics-temporary-storage",
    USTOM = "ics-custom",
    DIT_I = "ics-edit-i",
    IDONGX = "ics-yidongx",
}

interface Props extends HTMLAttributes<HTMLSpanElement> {
    type: IconClass;
    text?: string;
    textPosition: "left" | "right";
}

export default class Component extends React.PureComponent<Props> {
    public static defaultProps = {
        textPosition: "right",
    };

    render() {
        const {type, text, textPosition, className, ...restProps} = this.props;
        return <i className={`iconfont ${type} ${className ? className : ""}`} {...restProps} />;
    }
}
